<a href="https://colab.research.google.com/github/UiinKim/NLP_First/blob/main/2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.1.1 벡터와 행렬

In [ ]:
#모든 벡터는 행벡터로 다룬다
#vector x, matrix W
import numpy as np

x=np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [ ]:
x.shape

(3,)

In [ ]:
x.ndim

1

In [ ]:
W=np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [ ]:
W.ndim

2

In [ ]:
#vector, matrix는 np.array()로 생성
#shape은 다차원 배열의 형상 -> vector : 원소의 수가 3개, matrix : 2차원 배열로 각 차원별로 3개의 원소 총 6개의 원소가 존재
#ndim은 차원의 수 -> vector : 1차원, matrix : 2차원

1.1.2 행렬의 원소별 연산

In [ ]:
W=np.array([[1, 2, 3], [4, 5, 6]])
X=np.array([[0, 1, 2], [3, 4, 5]])
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [ ]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

1.1.3 브로드캐스트

In [ ]:
A=np.array([[1, 2], [3, 4]])
A*10

array([[10, 20],
       [30, 40]])

In [ ]:
#2x2 행렬에 스칼라 값인 10을 곱하여 스칼라 값 10이 2x2행렬로 확장된 후 원소별 연산 수행

In [ ]:
A=np.array([[1, 2], [3, 4]])
b=np.array([10, 20])
A*b

array([[10, 40],
       [30, 80]])

1.1.4 벡터의 내적과 행렬의 곱

In [ ]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])

In [ ]:
np.dot(a, b)
#x내적y는 x와 y의 원소들의 모든 곱의 합

32

In [ ]:
A=np.array([[1, 2], [3, 4]])
B=np.array([[5, 6], [7, 8]])

In [ ]:
#행렬곱은 각 행과 열에 맞는 값들을 곱하여 계산 (1x5 + 2x7 = 19)
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

1.2.1 신경망

In [ ]:
W1=np.random.randn(2, 4)
b1=np.random.randn(4)
x=np.random.randn(10, 2)
h=np.matmul(x, W1)+b1

In [ ]:
#FC는 선형 변환
#비선형 효과를 부여 : 활성화 함수 -> sigmoid(S자)

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
a=sigmoid(h)

In [ ]:
x=np.random.randn(10, 2) #2차원의 데이터 10개가 미니배치로 처리
W1=np.random.randn(2, 4)
b1=np.random.randn(4)
W2=np.random.randn(4, 3)
b2=np.random.randn(3)

h=np.matmul(x, W1) + b1
a=sigmoid(h)
s=np.matmul(a, W2) + b2 #(10, 3) shape
#s는 3차원으로 출력이 되며 3가지의 분류 케이스 점수(확률이 되기 전 score) -> softmax를 거쳐서 확률이 됨


1.2.2 계층으로 클래스화 및 순전파 구현

In [ ]:
class Sigmoid:
    def __init__(self):
        self.params=[] #가중치와 편향 같은 parameters 담는 리스트

    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [ ]:
class Affine:
    def __init__(self, W, b):
        self.params=[W, b]

    def forward(self, x):
        W, b = self.params #신경망이 학습될 때 수시로 갱신
        out = np.matmul(x, W) + b
        return out

In [ ]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        #가중치 및 편향 초기화
        W1=np.random.randn(I, H)
        b1=np.random.randn(H)
        W2=np.random.randn(H, O)
        b2=np.random.randn(O)

        #계층 생성
        self.layers=[
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        #모든 가중치를 리스트에 모은다.
        self.params=[]
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [ ]:
#예측해보기
x=np.random.randn(10, 2)
model=TwoLayerNet(2, 4, 3)
s=model.predict(x)
print(s)

[[-0.09611793  0.9182776  -0.1870312 ]
 [-0.65746549  0.7134409  -0.92772757]
 [-0.55644143  0.83206906 -0.93542695]
 [-0.28308649  0.76701186 -0.35761376]
 [-0.45980443  0.86420867 -0.77239211]
 [-0.53766125  0.81183541 -0.849522  ]
 [-0.23998178  0.72896561 -0.21746912]
 [-0.48715621  0.85331573 -0.81224785]
 [-0.48094816  0.86869192 -0.82724536]
 [-0.49308095  0.83313678 -0.79336479]]


1.3 노드

In [ ]:
D, N = 8, 7
x=np.random.randn(1, D) #input
y=np.repeat(x, N, axis=0) #forward
dy=np.random.randn(N, D) #무작위 기울기
dx=np.sum(dy, axis=0, keepdims=True) #backward, 차원 유지

In [ ]:
D, N=8, 7
x=np.random.randn(N, D) #input
y=np.sum(x, axis=0, keepdims=True) #forward -> 하나로 합쳐짐

dy=np.random.randn(1, D) #random 기울기
dx=np.repeat(dy, N, axis=0) # backward

In [ ]:
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)] #grads에 기울기 W보관하기 위해 리스트 선언
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.matmul(x, W)
        self.x = x
        return out

    def backward(self, dout):
        W, = self.params
        dx = np.matmul(dout, W.T) #x이므로 W.T와 dout
        dW = np.matmul(self.x.T, dout) #W이므로 x.T와 dout
        self.grads[0][...] = dW #역전파가 된 기울기를 grads에 보관
        #생략기호 ...을 활용하여 덮어쓰기 수행 -> 메모리 주소 고정된 자리에 복사(리스트이기 때문에 중요)
        return dx

In [ ]:
a=np.array([1, 2, 3])
b=np.array([4,5,6])

In [ ]:
#a=b를 하면 a가 b로 메모리 위치가 같아지는 것이고
#a[...]=b를 하면 메모리 위치가 아닌 내용 4, 5, 6만 복사하여 a의 해당된 메모리에 저장하는 것

1.3.5 기울기 도출과 역전파 구현

In [ ]:
#sigmoid의 식을 미분하면 y(1-y) -> y:output
class Sigmoid:
    def __init__(self):
        self.params, self.grads = [], []
        self.out=None

    def forward(self, x):
        out = 1 / (1+np.exp(-x))
        self.out=out
        return out

    def backward(self, dout):
        dx=dout * (1.0-self.out)*self.out
        return dx

In [ ]:
#Affine 층은 fully connected 층으로 x*W에 b를 더하는데 b는 은닉층과 x의 수 N에 맞춰 결정됨
class Affine:
    def __init__(self, W, b):
        self.params=[W, b]
        self.grads=[np.zeros_like(W), np.zeros_like(b)]
        self.x=None

    def forward(self, x):
        W, b=self.params
        out=np.matmul(x, W)+b #b는 브로드캐스팅 되어서 자동으로 N개 적용(repeat)
        self.x=x
        return out

    def backward(self, dout):
        W, b=self.params
        dx=np.matmul(dout, W.T)
        dW=np.matmul(self.x.T, dout)
        db=np.sum(dout, axis=0)

        self.grads[0][...]=dW
        self.grads[1][...]=db
        return dx

In [ ]:
class SGD:
    def __init__(self, lr=0.01):
        self.lr=lr

    def update(self, params, grads):
        for i in range(len(params)):

            params[i]-=self.lr*grads[i]

In [ ]:
def relu(x):
    return np.maximum(0, x)

def softmax(x):
    if x.ndim==2:
        x=x-x.max(axis=1, keepdims=True)
        x=np.exp(x)
        x/=x.sum(axis=1, keepdims=True)

    elif x.ndim==1:
        x=x-np.max(x)
        x=np.exp(x)/np.sum(np.exp(x))

    return x

def cross_entropy_error(y, t):
    if y.ndim==1:
        t=t.reshape(1, t.size)
        y=y.reshape(1, y.size)

    #정답데이터가 원핫 벡터일 경우 정답 레이블 인덱스로 변환
    if t.size==y.size:
        t=t.argmax(axis=1)

    batch_size=y.shape[0]

    return -np.sum(np.log(y[np.arange(batch_size), t]+1e-7))/batch_size

In [ ]:
class Softmax:
    def __init__(self):
        params, grads=[], []
        self.out=None

    def forward(self, x):
        self.out=softmax(x)
        return self.out

    def backward(self, dout):
        dx=self.out*dout #역전파로 구한 순전파의 출력에 대한 기울기를 곱하여 dx를 구한다
        sumdx=np.sum(dx, axis=1, keepdims=True) #axis=1로 설정하여 각 dx값마다의 합을 구한다
        dx-=self.out*sumdx
        return dx

class SoftmaxWithLoss:
    def __init__(self):
        self.params, self.grads=[], []
        self.y=None #softmax의 출력
        self.t=None #정답 레이블

    def forward(self, x, t):
        self.t=t
        self.y=softmax(x)

        #정답 레이블이 원핫베터면 그대로 정답 인덱스로 변환
        if self.t.size==self.y.size:
            self.t=self.t.argmax(axis=1) #가장 확률이 높은 인덱스 반환

        loss=cross_entropy_error(self.y, self.t)
        return loss

    def backward(self, dout=1):
        batch_size=self.t.shape[0] #정답 레이블의 batch_size 복사

        dx=self.y.copy()
        dx[np.arange(batch_size), self.t] -= 1
        dx*=dout
        dx=dx/batch_size

        return dx

In [ ]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O=input_size, hidden_size, output_size

        #가중치, 편향 초기화
        W1=0.01*np.random.randn(I, H) #가중치를 작은 무작위 값으로 초기화
        b1=np.zeros(H)
        W2=0.01*np.random.randn(H, O)
        b2=np.zeros(O)

        #계층 생성
        self.layers=[
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        self.loss_layer=SoftmaxWithLoss()

        #모든 가중치와 기울기를 리스트에 모은다.
        self.params, self.grads=[],[]
        for layer in self.layers:
            self.params+=layer.params
            self.grads+=layer.grads

    def predict(self, x): #순전파로 출력값 계산
        for layer in self.layers:
            x=layer.forward(x)
        return x

    def forward(self, x, t): #input x와 label t를 받아 순전파를 수행하면서 loss 계산
        score=self.predict(x)
        loss=self.loss_layer.forward(score, t) #softmaxwithloss 계층
        return loss

    def backward(self, dout=1): #loss의 기울기인 dout을 받아 역전파를 수행하며 각 계층의 기울기 계산
        dout=self.loss_layer.backward(dout)
        for layer in reversed(self.layers): #역층 순으로 역전파 계산하며 기울기 전달
            dout=layer.backward(dout)
        return dout



In [ ]:
def load_data(seed=1984):
    np.random.seed(seed)
    N = 100  # 클래스당 샘플 수
    DIM = 2  # 데어터 요소 수
    CLS_NUM = 3  # 클래스 수

    x = np.zeros((N*CLS_NUM, DIM))
    t = np.zeros((N*CLS_NUM, CLS_NUM), dtype=np.int)

    for j in range(CLS_NUM):
        for i in range(N): # N*j, N*(j+1)):
            rate = i / N
            radius = 1.0*rate
            theta = j*4.0 + 4.0*rate + np.random.randn()*0.2

            ix = N*j + i
            x[ix] = np.array([radius*np.sin(theta),
                              radius*np.cos(theta)]).flatten()
            t[ix, j] = 1

    return x, t

In [ ]:
#train code

#하이퍼파라미터 설정
max_epoch=300
batch_size=30
hidden_size=10
learning_rate=1.0

#데이터 읽기, 모델과 옵티마이저 생성
x, t=load_data()
model=TwoLayerNet(input_size=2, hidden_size=hidden_size, output_size=3)
optimizer=SGD(lr=learning_rate)

#학습에 사용하는 변수
data_size=len(x)
max_iters=data_size//batch_size
total_loss=0
loss_count=0
loss_list=[]

for epoch in range(max_epoch):
    #데이터 shuffle
    idx=np.random.permutation(data_size)
    x=x[idx]
    t=t[idx]

    for iters in range(max_iters):
        batch_x=x[iters*batch_size:(iters+1)*batch_size]
        batch_t=t[iters*batch_size:(iters+1)*batch_size]

        #기울기를 구하여 파라미터 갱신
        loss=model.forward(batch_x, batch_t)
        model.backward()
        optimizer.update(model.params, model.grads)

        total_loss+=loss
        loss_count+=1

        #정기적으로 학습 결과 출력
        if (iters+1)%10==0:
            avg_loss=total_loss/loss_count
            print('| 에폭 %d |  반복 %d / %d | 손실 %.2f' % (epoch + 1, iters + 1, max_iters, avg_loss))
            loss_list.append(avg_loss)
            total_loss, loss_count=0,0


/home/LFC/.conda/envs/musicgen/lib/python3.7/site-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


| 에폭 1 |  반복 10 / 10 | 손실 1.13
| 에폭 2 |  반복 10 / 10 | 손실 1.13
| 에폭 3 |  반복 10 / 10 | 손실 1.12
| 에폭 4 |  반복 10 / 10 | 손실 1.12
| 에폭 5 |  반복 10 / 10 | 손실 1.11
| 에폭 6 |  반복 10 / 10 | 손실 1.14
| 에폭 7 |  반복 10 / 10 | 손실 1.16
| 에폭 8 |  반복 10 / 10 | 손실 1.11
| 에폭 9 |  반복 10 / 10 | 손실 1.12
| 에폭 10 |  반복 10 / 10 | 손실 1.13
| 에폭 11 |  반복 10 / 10 | 손실 1.12
| 에폭 12 |  반복 10 / 10 | 손실 1.11
| 에폭 13 |  반복 10 / 10 | 손실 1.09
| 에폭 14 |  반복 10 / 10 | 손실 1.08
| 에폭 15 |  반복 10 / 10 | 손실 1.04
| 에폭 16 |  반복 10 / 10 | 손실 1.03
| 에폭 17 |  반복 10 / 10 | 손실 0.96
| 에폭 18 |  반복 10 / 10 | 손실 0.92
| 에폭 19 |  반복 10 / 10 | 손실 0.92
| 에폭 20 |  반복 10 / 10 | 손실 0.87
| 에폭 21 |  반복 10 / 10 | 손실 0.85
| 에폭 22 |  반복 10 / 10 | 손실 0.82
| 에폭 23 |  반복 10 / 10 | 손실 0.79
| 에폭 24 |  반복 10 / 10 | 손실 0.78
| 에폭 25 |  반복 10 / 10 | 손실 0.82
| 에폭 26 |  반복 10 / 10 | 손실 0.78
| 에폭 27 |  반복 10 / 10 | 손실 0.76
| 에폭 28 |  반복 10 / 10 | 손실 0.76
| 에폭 29 |  반복 10 / 10 | 손실 0.78
| 에폭 30 |  반복 10 / 10 | 손실 0.75
| 에폭 31 |  반복 10 / 10 | 손실 0.78
| 에폭 32 |  반복 10 