<a href="https://colab.research.google.com/github/UiinKim/UiinKim/blob/main/Latent_Semantic_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
#Full SVD
import numpy as np

In [19]:
A=np.array([[0,0,0,1,0,1,1,0,0],[0,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,0,0],[1,0,0,0,0,0,0,1,1]])
print('DTM의 크기 : ', A.shape)

DTM의 크기 :  (4, 9)


In [20]:
U, s, VT=np.linalg.svd(A, full_matrices=True)
#직교행렬
print('행렬 U : ')
print(U.round(2))#소수점 2자리까지만 표현
print('행렬 U의 크기 : ', np.shape(U))

행렬 U : 
[[-0.24  0.75  0.   -0.62]
 [-0.51  0.44 -0.    0.74]
 [-0.83 -0.49 -0.   -0.27]
 [-0.   -0.    1.    0.  ]]
행렬 U의 크기 :  (4, 4)


In [21]:
#대각행렬(linalg.svd의 영향으로 대각행렬이 아닌 리스트로 반환됨)
print('특이값 벡터(s)')
print(s.round(2))
print('특이값 벡터의 크기 : ', s.shape)

특이값 벡터(s)
[2.69 2.05 1.73 0.77]
특이값 벡터의 크기 :  (4,)


In [22]:
#대각 행렬의 크기인 4 X 9의 크기로 행렬 생성
S=np.zeros((4,9))

#특이값을 대각행렬에 삽입
S[:4,:4]=np.diag(s) #대각으로 삽입(diag)

print('대각행렬 S : ')
print(S.round(2))

print('대각행렬의 크기 : ')
print(np.shape(S))

대각행렬 S : 
[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]
대각행렬의 크기 : 
(4, 9)


In [23]:
print('직교행렬 VT : ')
print(VT.round(2))

print('직교 행렬 VT의 크기 : ')
print(VT.shape)

직교행렬 VT : 
[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]
직교 행렬 VT의 크기 : 
(9, 9)


In [24]:
np.allclose(A, np.dot(np.dot(U,S),VT).round(2))

True

In [25]:
#Truncated SVD
#특이값 상위 2개만 보존
S=S[:2,:2]

print('대각 행렬 S : ')
print(S.round(2))

대각 행렬 S : 
[[2.69 0.  ]
 [0.   2.05]]


In [26]:
U=U[:,:2]
print('행렬 U : ')
print(U.round(2))

행렬 U : 
[[-0.24  0.75]
 [-0.51  0.44]
 [-0.83 -0.49]
 [-0.   -0.  ]]


In [27]:
VT=VT[:2,:] #V의 입장에서는 2개의 열만 추출
print('직교 행렬 VT : ')
print(VT.round(2))

직교 행렬 VT : 
[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]


In [28]:
A_prime=np.dot(np.dot(U,S),VT)
print(A)
print(A_prime.round(2))

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]


In [29]:
#실습
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

In [30]:
dataset=fetch_20newsgroups(shuffle=True, random_state=1, remove=('header', 'footers', 'quotes'))
documents=dataset.data
print('샘플의 수 : ', len(documents))

샘플의 수 :  11314


In [31]:
documents[1]

"From: timmbake@mcl.ucsb.edu (Bake Timmons)\nSubject: Re: Amusing atheists and agnostics\nLines: 66\n\n\n\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n\n\n\n\n\n\nJim,\n\nSorry I can't pity you, Jim.  And I'm sorry that you have these feelings of\ndenial about the faith you need to get by.  Oh well, just pretend that it will\nall end happily ever after anyway.  Maybe if you start a new newsgroup,\nalt.atheist.hard, you won't be bummin' so much?\n\n\n\n\n\n\nBye-Bye, Big Jim.  Don't forget your Flintstone's Chewables!  :) \n--\nBake Timmons, III"

In [32]:
print(dataset.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [35]:
news_df = pd.DataFrame({'document':documents})
# 특수 문자 제거
news_df['clean_doc'] = news_df['document'].str.replace("[^a-zA-Z]", " ")
# 길이가 3이하인 단어는 제거 (길이가 짧은 단어 제거)
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))
# 전체 단어에 대한 소문자 변환
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: x.lower())

<ipython-input-35-b4124dfb5e6a>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  news_df['clean_doc'] = news_df['document'].str.replace("[^a-zA-Z]", " ")


In [36]:
news_df['clean_doc'][1]

'from timmbake ucsb bake timmons subject amusing atheists agnostics lines yeah expect people read actually accept hard atheism need little leap faith jimmy your logic runs steam sorry pity sorry that have these feelings denial about faith need well just pretend that will happily ever after anyway maybe start newsgroup atheist hard bummin much forget your flintstone chewables bake timmons'

In [38]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [42]:
#NLTK로부터 불용어를 받아온다.
stop_words=stopwords.words('english')
tokenized_doc=news_df['clean_doc'].apply(lambda x:x.split()) #토큰화
tokenized_doc = tokenized_doc.apply(lambda x: [item for item in x if item not in stop_words])
# 불용어를 제거합니다.

In [43]:
#역토큰화
detokenized_doc=[]
for i in range(len(news_df)):
  t=' '.join(tokenized_doc[i])
  detokenized_doc.append(t)

news_df['clean_doc']=detokenized_doc

In [51]:
vectorizer = TfidfVectorizer(stop_words='english', max_features= 1000, # 상위 1,000개의 단어를 보존
max_df = 0.5, smooth_idf=True)

X = vectorizer.fit_transform(news_df['clean_doc'])

# TF-IDF 행렬의 크기 확인
print('TF-IDF 행렬의 크기 :',X.shape)


TF-IDF 행렬의 크기 : (11314, 1000)


In [52]:
svd_model = TruncatedSVD(n_components=20, algorithm='randomized', n_iter=100, random_state=122)
svd_model.fit(X)
len(svd_model.components_)


20

In [53]:
np.shape(svd_model.components_)

(20, 1000)

In [56]:
terms = vectorizer.get_feature_names_out() # 단어 집합. 1,000개의 단어가 저장됨.

def get_topics(components, feature_names, n=5):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [(feature_names[i], topic[i].round(5)) for i in topic.argsort()[:-n - 1:-1]])
get_topics(svd_model.components_,terms)


Topic 1: [('posting', 0.27494), ('host', 0.26886), ('nntp', 0.2688), ('university', 0.2218), ('distribution', 0.16715)]
Topic 2: [('nntp', 0.40741), ('host', 0.40479), ('posting', 0.40086), ('university', 0.15704), ('distribution', 0.13024)]
Topic 3: [('windows', 0.39271), ('card', 0.18234), ('file', 0.16217), ('thanks', 0.15766), ('drive', 0.15256)]
Topic 4: [('university', 0.47298), ('state', 0.32655), ('ohio', 0.21727), ('cleveland', 0.15398), ('virginia', 0.14866)]
Topic 5: [('pitt', 0.46305), ('gordon', 0.4018), ('banks', 0.39252), ('computer', 0.22558), ('science', 0.21242)]
Topic 6: [('cleveland', 0.35839), ('cwru', 0.34055), ('freenet', 0.2414), ('reserve', 0.19872), ('western', 0.1983)]
Topic 7: [('nasa', 0.31696), ('state', 0.27449), ('access', 0.26734), ('ohio', 0.23291), ('space', 0.18938)]
Topic 8: [('nasa', 0.5096), ('space', 0.30749), ('cleveland', 0.22575), ('cwru', 0.1883), ('team', 0.14418)]
Topic 9: [('access', 0.30755), ('sale', 0.22276), ('drive', 0.2077), ('digex'