<a href="https://colab.research.google.com/github/UiinKim/UiinKim/blob/main/NLP_%ED%85%8D%EC%8A%A4%ED%8A%B8_%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  1. 토큰화 -> 토큰으로 나누는 기준마다 다르다(단어, 문장 등)

In [73]:

from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from nltk.tokenize import TreebankWordTokenizer

In [74]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [75]:
#단어 토큰화에서는 단순 띄어쓰기, 어퍼스트로피, 특수문자로 구분해서는 안된다.
sentence="Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."
print(word_tokenize(sentence))
print(WordPunctTokenizer().tokenize(sentence))
print(text_to_word_sequence(sentence))
print(TreebankWordTokenizer().tokenize(sentence))
#토큰화 도구마다 말뭉치(코퍼스)가 다르다
#

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']
['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']
["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']
['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [76]:
#문장 토큰화에서는 '.'으로 구분하면 ip주소나 이메일에서 걸린다.
from nltk.tokenize import sent_tokenize

text="His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."
print(sent_tokenize(text))
#밑에는 마침표가 여러개 등장하는 경우
text_cf="I am actively looking for Ph.D. students. and you are a Ph.D student."
print(sent_tokenize(text_cf))

['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']
['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


In [77]:
!pip install kss
#kss는 한국어 문장 토큰화 도구

In [78]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [79]:
import kss

text='딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다. 이제 해보면 알걸요?'
print(kss.split_sentences(text))
#한국어는 영어와 달리 어절 토큰화가 아닌 형태소 토큰화를 시켜야한다.

['딥 러닝 자연어 처리가 재미있기는 합니다.', '그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다.', '이제 해보면 알걸요?']


품사태깅 한국어의 '못', 영어의 'fly' -> 의미를 명확하게 알기 위해서 사용

In [80]:
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag

text="I am actively looking for Ph.D. students. and you are a Ph.D. student."
tokenized_sentence=word_tokenize(text)
print('단어 토큰화 : {}'.format(tokenized_sentence))
print('품사 태깅 : {}'.format(pos_tag(tokenized_sentence)))
#PRP는 인칭대명사, VBP는 동사, RB는 부사, VBG는 현재부사, IN은 전치사, NNP는 고유명사, NNS는 복수형 명사, CC는 접속사, DT는 관사

단어 토큰화 : ['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D.', 'student', '.']
품사 태깅 : [('I', 'PRP'), ('am', 'VBP'), ('actively', 'RB'), ('looking', 'VBG'), ('for', 'IN'), ('Ph.D.', 'NNP'), ('students', 'NNS'), ('.', '.'), ('and', 'CC'), ('you', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('Ph.D.', 'NNP'), ('student', 'NN'), ('.', '.')]


In [81]:
!pip install konlpy

In [82]:
from konlpy.tag import Okt
from konlpy.tag import Kkma

okt=Okt()
kkma=Kkma()

text="열심히 코딩한 당신, 연휴에는 여행을 가봐요"

print('OKT 형태소 분석 : {}'.format(okt.morphs(text)))
print('Kkma 형태소 분석 : {}'.format(kkma.morphs(text)))
print('OKT 품사 태깅 : {}'.format(okt.pos(text)))
print('Kkma 품사 태깅 : {}'.format(kkma.pos(text)))
print('OKT 명사 추출 : {}'.format(okt.nouns(text)))
print('Kkma 명사 추출 : {}'.format(kkma.nouns(text)))

OKT 형태소 분석 : ['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']
Kkma 형태소 분석 : ['열심히', '코딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을', '가보', '아요']
OKT 품사 태깅 : [('열심히', 'Adverb'), ('코딩', 'Noun'), ('한', 'Josa'), ('당신', 'Noun'), (',', 'Punctuation'), ('연휴', 'Noun'), ('에는', 'Josa'), ('여행', 'Noun'), ('을', 'Josa'), ('가봐요', 'Verb')]
Kkma 품사 태깅 : [('열심히', 'MAG'), ('코딩', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('당신', 'NP'), (',', 'SP'), ('연휴', 'NNG'), ('에', 'JKM'), ('는', 'JX'), ('여행', 'NNG'), ('을', 'JKO'), ('가보', 'VV'), ('아요', 'EFN')]
OKT 명사 추출 : ['코딩', '당신', '연휴', '여행']
Kkma 명사 추출 : ['코딩', '당신', '연휴', '여행']


 2.정제(코퍼스에서 노이즈 데이터--> 등장 빈도가 낮은 단어, 길이가 짧은 단어 제거) 및 정규화(표현 방법이 다른 단어들을 통합)

In [83]:
import re #regular expression 정규표현식
text="I was wondering if anyone out there could enlighten me on this car."

#단어의 길이 1~2인 단어를 정규표현식으로 삭제
shortword=re.compile(r'\W*\b\w{1,2}\b')
#compile 정규식 개체 리턴
print(shortword.sub('',text))

 was wondering anyone out there could enlighten this car.


In [84]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

3. 정규화 기법 : 어간 추출, 표제어(사전에 있는 단어) 추출 --> 하나의 단어로 일반화 시킬 수 있으면 문서 내의 단어의 수를 줄이겠다 -> BoW(Bag of Word)에서 사용

 표제어 추출

In [85]:
#표제어(Lemma) : are, is, am -> be
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']

print('표제어 추출 전 : {}'.format(words))
print('표제어 추출 후 : {}'.format([lemmatizer.lemmatize(word) for word in words]))

표제어 추출 전 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
표제어 추출 후 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


In [86]:
#WordNetLemmatizer은 품사를 알려주면 품사의 정보를 보존하며 정확학 Lemma가 추출된다.
print(lemmatizer.lemmatize('dies', 'v'))
print(lemmatizer.lemmatize('has', 'v'))
print(lemmatizer.lemmatize('watched', 'v'))

die
have
watch


어간(Stem) 추출

In [87]:

from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
stemmer=PorterStemmer()

sentence="This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."
tokenized_sentence=word_tokenize(sentence)
print('어간 추출 전 : {}'.format(tokenized_sentence))
print('어간 추출 후 : {}'.format([stemmer.stem(word) for word in tokenized_sentence]))

어간 추출 전 : ['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']
어간 추출 후 : ['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']


In [88]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer

porter_stemmer=PorterStemmer()
lancaster_stemmer=LancasterStemmer()

words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print('포터스태머 : ', [porter_stemmer.stem(word) for word in words])
print('랭커스태머 : ', [lancaster_stemmer.stem(word) for word in words])
#알고리즘이 다르기 때문에 매우 다른 결과가 나온다. 표제어 추출과도 매우 다르게 나온다.

포터스태머 :  ['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'watch', 'ha', 'start']
랭커스태머 :  ['policy', 'doing', 'org', 'hav', 'going', 'lov', 'liv', 'fly', 'die', 'watch', 'has', 'start']


4. 불용어 : 자주 등장하지만 분석을 하는데에 불필요한 단어


In [89]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from konlpy.tag import Okt

In [90]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [91]:
stop_word_list=stopwords.words('english')
print('불용어의 개수 : {}'.format(len(stop_word_list)))
print('영어의 불용어 10개 출력 : {}'.format(stop_word_list[:10]))

불용어의 개수 : 179
영어의 불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


In [92]:
#NLTK를 통해 불용어 제거하기
example="Family is not an important thing. It's everything."
stop_words=set(stopwords.words('english'))

tokenized_sentence=word_tokenize(example)

result=[]
for word in tokenized_sentence:
  if word not in stop_words:
    result.append(word)

print("불용어 제거 전 : {}".format(tokenized_sentence))
print('불용어 제거 후 : {}'.format(result))

불용어 제거 전 : ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후 : ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [93]:
#한국어 불용어 제거하기(절대적인 기준이 아니므로 사용자 설정을 하는 경우가 많음)
okt=Okt()
example="고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_words="를 아무렇게나 구 우려 고 안 돼 같은 게 구울 때 는"

stop_words=set(stop_words.split(' '))
word_tokens=okt.morphs(example)

result=[word for word in word_tokens if not word in stop_words]

print('불용어 제거 전 : {}'.format(word_tokens))
print('불용어 제거 후 : {}'.format(result))

불용어 제거 전 : ['고기', '를', '아무렇게나', '구', '우려', '고', '하면', '안', '돼', '.', '고기', '라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살', '을', '구울', '때', '는', '중요한', '게', '있지', '.']
불용어 제거 후 : ['고기', '하면', '.', '고기', '라고', '다', '아니거든', '.', '예컨대', '삼겹살', '을', '중요한', '있지', '.']


5. 정규표현식 -> re와 nltk를 통해 토큰화하는데 유용



In [94]:
import re
r=re.compile('a.c')
r.search('kkk')
#아무것도 출력되지 않는다.

In [95]:
r.search('abc')
# '.'은 한 개의 임의의 문자를 나타낸다.

<re.Match object; span=(0, 3), match='abc'>

In [96]:
r=re.compile('ab?c')
r.search('abbbc')
#아무것도 출력되지 않는다.

In [97]:
r.search('abc')
# '?'앞의 문자인 b가 존재할 수도 있고 존재하지 않을 수도 있다

<re.Match object; span=(0, 3), match='abc'>

In [98]:
r.search('ac')

<re.Match object; span=(0, 2), match='ac'>

In [99]:
# . : 대체할 수 있다.
# ? : ? 앞의 문자가 존재할 수도 있고 존재하지 않을 수도 있다.
# * : * 앞의 문자가 0개 이상이다.
# + : + 앞의 문자가 1개 이상이다.
# ^ : ^ 뒤의 문자열이 모두 포함하여 시작되는 경우 매치한다.
# {숫자} : {숫자} 앞의 문자를 숫자만큼 반복하여 나타거나 매치한다.
# {숫자1, 숫자2} : {숫자 1, 숫자 2} 앞의 문자를 숫자 1과 숫자 2 사이만큼 반복하여 나타내거나 매치한다.
# {숫자, } : {숫자} 앞의 문자를 숫자 이상만큼 반복한다
# [] : [] 안의 문자들 중 한개의 문자와 매치한다. [A-Za-z]는 모든 알파벳을 의미하고 [0-9]는 숫자 전부를 의미한다.
# [^문자] : [^문자]를 제외한 모든 문자를 매치한다. [^abc]이면 a or b or c를 제외한 모든 문자


6. 정수 인코딩(정수와 텍스트를 맵핑)
6-1. dictionary 사용

In [100]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [101]:
raw_text="A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [102]:
#문장 토큰화
sentences=sent_tokenize(raw_text)
print(sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [103]:
#단어 정제(불용어)
vocab={}
preprocessed_sentence=[]
stop_words=set(stopwords.words('english'))

for sentence in sentences:
  #단어 토큰화
  tokenized_sentence=word_tokenize(sentence)
  result=[]

  for word in tokenized_sentence:
    word=word.lower() #모든 단어를 소문자화하여 단어의 개수를 줄인다.
    if word not in stop_words: #단어 토큰화 된 결과에 대해 불용어를 제거한다.
      if len(word) >2: #단어의 길이가 2 이하인 경우 추가로 단어를 제거한다.
        result.append(word)
        if word not in vocab:
          vocab[word]=0 #처음 등장인 경우 해당 단어를 0으로 초기화
        vocab[word]+=1 #등장한 횟수만큼 +1이 된다.
  preprocessed_sentence.append(result) #불용어를 제거한 단어들만 추가한다.
print(preprocessed_sentence)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [104]:
print('단어 집합 : ', vocab)
print('barber의 빈도 수 : ', vocab['barber'])
#빈도수 출력

단어 집합 :  {'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}
barber의 빈도 수 :  8


In [105]:
#빈도수대로 정렬
vocab_sorted=sorted(vocab.items(), key=lambda x:x[1], reverse=True)
# vocab.items()는 vocab의 key와 value를 모두 포함한다는 뜻이고 lambda는 새로운 x로 설정하고 싶은 값을 x:원하는 값으로 설정한다.
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [106]:
word_to_index={}
i=0 # 높은 빈도수를 가진 단어부터 1부터 입력
for(word, frequency) in vocab_sorted:
  if frequency > 1: #빈도수가 1회 이하이면 제외한다.
    i=i+1
    word_to_index[word]=i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [107]:
vocab_size=5
words_frequency=[word for word,index in word_to_index.items() if index>=vocab_size+1]
#인덱스가 5보다 높은 단어 들만 리스트에 저장
for word in words_frequency:
  del word_to_index[word] #word_frequency에 포함된 단어 제거
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [108]:
#단어들을 정수로 인코딩
#단어 집합에 존재하지 않는 단어들을 Out-Of_Vocabulary(OOV)라고 한다.
word_to_index['OOV']=len(word_to_index)+1 #OOV의 단어의 경우를 추가해준다.
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}


In [109]:
#word_to_index를 사용하여 sentences의 모든 단어들을 맵핑되는 정수로 인코딩
encoded_sentences=[]
for sentence in preprocessed_sentence:
  encoded_sentence=[]
  for word in sentence:
    try:
      #단어 집합에 있는 단어이면 해당 단어의 정수를 리턴.
      encoded_sentence.append(word_to_index[word])
    except KeyError:
      #없는 경우 'OOV'를 리턴
      encoded_sentence.append(word_to_index['OOV'])
  encoded_sentences.append(encoded_sentence)
print(encoded_sentences)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


2. Counter 사용하기

In [110]:
from collections import Counter #위의 dictionary로 일일이 저장하는 방법을 api로 불러와 간단하게 하는 방법
print(preprocessed_sentence)
#prerprocessed_sentence는 단어 토큰화의 결과만 저장되어 있어 단어 집합을 만들기 위해 ','를 제거하고 단어들을 하나의 리스트로 만든다.

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [111]:
all_words_list=sum(preprocessed_sentence, [])
print(all_words_list)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [112]:
vocab=Counter(all_words_list) #자동으로 빈도수에 따른 dictionary화 및 정렬
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [113]:
vocab_size=5
vocab=vocab.most_common(vocab_size) #vocab_size만큼 가장 빈도수가 많은 것만 저장
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [114]:
word_to_index={}
i=0
for(word, frequency) in vocab:
  i=i+1
  word_to_index[word]=i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


6-3. NLTK의 FreqDist 사용하기

In [115]:
from nltk import FreqDist
import numpy as np

In [116]:
# hstack은 행이 같으면 모든 리스트들을 column옆으로 쭉 추가한다. -> 문장 구분을 제거한다.
vocab=FreqDist(np.hstack(preprocessed_sentence)) #Counter와 같은 방법이다.

In [117]:
print(vocab['barber'])

8


In [118]:
vocab_size=5
vocab=vocab.most_common(vocab_size)
print(vocab)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]


In [119]:
#enumerate는 (인덱스, value)로 변환된다. 여기서 인덱스를 자동으로 구해주는 함수이다.
word_to_index={word[0]:index+1 for index, word in enumerate(vocab)}
#word는 vocab의 1튜플씩 나오며 word[0]은 (단어, 빈도수) 중에 단어에 해당한다. index는 enumerate를 통해 인덱스값이 추출 되며 +1을 하여 정수로 지정한다.
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [120]:
#enumerate 실습
#enumerate는 순서가 있는 자료형(list, set, tuple, dictionary, string)을 입력으로 받아 인덱스를 순차적으로 리턴
test_input=['a', 'b', 'c', 'd', 'e']
for index, value in enumerate(test_input):
  print("value : {}, index : {}".format(value, index))

value : a, index : 0
value : b, index : 1
value : c, index : 2
value : d, index : 3
value : e, index : 4


6-4. 케라스(Keras) 텍스트 전처리

In [121]:
from tensorflow.keras.preprocessing.text import Tokenizer
preprocessed_sentence

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [122]:
tokenizer=Tokenizer()

#fit_on_texts() 안에 코퍼스(preprocessed_sentence)를 입력으로 하면 빈도수를 기준으로 단어 집합 생성
tokenizer.fit_on_texts(preprocessed_sentence) #각 문장별로 총 단어 빈도수가 높은 순으로 낮은 인덱스를 부여한다.
print(tokenizer.word_index) #인덱스가 어떻게 부여되었는지 확인한다.
print(tokenizer.word_counts) #각 단어가 몇 개 였는지 확인한다.
print(tokenizer.texts_to_sequences(preprocessed_sentence)) #입력으로 들어온 코퍼스에 대해서 각 단어를 이미 정해진 인덱스로 변환한다.

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}
OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])
[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [123]:
vocab_size=5
tokenizer=Tokenizer(num_words=vocab_size+1)#상위단어 5개만 사용
tokenizer.fit_on_texts(preprocessed_sentence)
print(tokenizer.word_index)
print(tokenizer.word_counts)
print(tokenizer.texts_to_sequences(preprocessed_sentence)) #위의 두줄은 적용되지 않고 마지막 줄만 적용이 되어있다.

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}
OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])
[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [124]:
#한번에 적용을 하는 방법
tokenizer=Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentence)
vocab_size=5
words_frequency=[word for word, index in tokenizer.word_index.items() if index>=vocab_size+1]

for word in words_frequency:
  del tokenizer.word_index[word]
  del tokenizer.word_counts[word]

print(tokenizer.word_index)
print(tokenizer.word_counts)
print(tokenizer.texts_to_sequences(preprocessed_sentence))

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}
OrderedDict([('barber', 8), ('person', 3), ('huge', 5), ('secret', 6), ('kept', 4)])
[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [125]:
#keras의 tokenizer은 기본적으로 단어 집합에 없는 OOV는 삭제를 해버린다.
#이에 대한 보완으로 oov_token에 OOV를 추가하여 사용할 수 있다.
#숫자 0과 OOV를 고려해서 단어 집합의 크기는 +2
vocab_size=5
tokenizer=Tokenizer(num_words=vocab_size+2, oov_token='OOV')
tokenizer.fit_on_texts(preprocessed_sentence)
print('OOV의 인덱스 : ', tokenizer.word_index['OOV'])
#기본적으로 keras tokenizer은 OOV의 인덱스를 1로 설정한다.

OOV의 인덱스 :  1


In [126]:
#모두 확인이 끝나면 정수 인코딩
print(tokenizer.texts_to_sequences(preprocessed_sentence))

[[2, 6], [2, 1, 6], [2, 4, 6], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


7. 패딩(padding)

In [127]:
#Numpy로 패딩하기
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.tokenize import stopwords

ll='Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry. The main story arc concerns Harry\'s conflict with Lord Voldemort, a dark wizard who intends to become immortal, overthrow the wizard governing body known as the Ministry of Magic and subjugate all wizards and Muggles (non-magical people). The series was originally published in English by Bloomsbury in the United Kingdom and Scholastic Press in the United States. All versions around the world are printed by Grafica Veneta in Italy.[1] A series of many genres, including fantasy, drama, coming-of-age fiction, and the British school story (which includes elements of mystery, thriller, adventure, horror, and romance), the world of Harry Potter explores numerous themes and includes many cultural meanings and references.[2] According to Rowling, the main theme is death.[3] Other major themes in the series include prejudice, corruption, and madness.[4] Since the release of the first novel, Harry Potter and the Philosopher\'s Stone, on 26 June 1997, the books have found immense popularity, positive reviews, and commercial success worldwide. They have attracted a wide adult audience as well as younger readers and are widely considered cornerstones of modern literature.[5][6] As of February 2023, the books have sold more than 600 million copies worldwide, making them the best-selling book series in history, and have been available in 85 languages.[7] The last four books consecutively set records as the fastest-selling books in history, with the final instalment selling roughly 2.7 million copies in the United Kingdom and 8.3 million copies in the United States within twenty-four hours of its release. The original seven books were adapted into an eight-part namesake film series by Warner Bros. Pictures. In 2016, the total value of the Harry Potter franchise was estimated at $25 billion,[8] making Harry Potter one of the highest-grossing media franchises of all time. Harry Potter and the Cursed Child is a play based on a story co-written by Rowling. The success of the books and films has allowed the Harry Potter franchise to expand with numerous derivative works, a travelling exhibition that premiered in Chicago in 2009, a studio tour in London that opened in 2012, a digital platform on which J. K. Rowling updates the series with new information and insight, and a pentalogy of spin-off films premiering in November 2016 with Fantastic Beasts and Where to Find Them, among many other developments. Themed attractions, collectively known as The Wizarding World of Harry Potter, have been built at several Universal Destinations & Experiences amusement parks around the world.'
sentences=sent_tokenize(ll)
print(sentences)


['Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling.', 'The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry.', "The main story arc concerns Harry's conflict with Lord Voldemort, a dark wizard who intends to become immortal, overthrow the wizard governing body known as the Ministry of Magic and subjugate all wizards and Muggles (non-magical people).", 'The series was originally published in English by Bloomsbury in the United Kingdom and Scholastic Press in the United States.', 'All versions around the world are printed by Grafica Veneta in Italy.', '[1] A series of many genres, including fantasy, drama, coming-of-age fiction, and the British school story (which includes elements of mystery, thriller, adventure, horror, and romance), the world of Harry Potter explores numerous themes and includes many cultural meaning

In [144]:
vocab={}
preprocessed_sentences=[]
wordstop=set(stopwords.words('english'))
for sentence in sentences:
  result=[]
  tokenized_sentence=word_tokenize(sentence.lower())
  for word in tokenized_sentence:
    if word not in wordstop:
      if len(word)>2:
        result.append(word)
        if word not in vocab:
          vocab[word]=0
        vocab[word]+=1
  preprocessed_sentences.append(result)
print(preprocessed_sentences)

[['harry', 'potter', 'series', 'seven', 'fantasy', 'novels', 'written', 'british', 'author', 'rowling'], ['novels', 'chronicle', 'lives', 'young', 'wizard', 'harry', 'potter', 'friends', 'hermione', 'granger', 'ron', 'weasley', 'students', 'hogwarts', 'school', 'witchcraft', 'wizardry'], ['main', 'story', 'arc', 'concerns', 'harry', 'conflict', 'lord', 'voldemort', 'dark', 'wizard', 'intends', 'become', 'immortal', 'overthrow', 'wizard', 'governing', 'body', 'known', 'ministry', 'magic', 'subjugate', 'wizards', 'muggles', 'non-magical', 'people'], ['series', 'originally', 'published', 'english', 'bloomsbury', 'united', 'kingdom', 'scholastic', 'press', 'united', 'states'], ['versions', 'around', 'world', 'printed', 'grafica', 'veneta', 'italy'], ['series', 'many', 'genres', 'including', 'fantasy', 'drama', 'coming-of-age', 'fiction', 'british', 'school', 'story', 'includes', 'elements', 'mystery', 'thriller', 'adventure', 'horror', 'romance', 'world', 'harry', 'potter', 'explores', 'nu

In [146]:
print(vocab)
print(vocab['harry'])

{'harry': 10, 'potter': 9, 'series': 7, 'seven': 2, 'fantasy': 2, 'novels': 2, 'written': 1, 'british': 2, 'author': 1, 'rowling': 4, 'chronicle': 1, 'lives': 1, 'young': 1, 'wizard': 3, 'friends': 1, 'hermione': 1, 'granger': 1, 'ron': 1, 'weasley': 1, 'students': 1, 'hogwarts': 1, 'school': 2, 'witchcraft': 1, 'wizardry': 1, 'main': 2, 'story': 3, 'arc': 1, 'concerns': 1, 'conflict': 1, 'lord': 1, 'voldemort': 1, 'dark': 1, 'intends': 1, 'become': 1, 'immortal': 1, 'overthrow': 1, 'governing': 1, 'body': 1, 'known': 2, 'ministry': 1, 'magic': 1, 'subjugate': 1, 'wizards': 1, 'muggles': 1, 'non-magical': 1, 'people': 1, 'originally': 1, 'published': 1, 'english': 1, 'bloomsbury': 1, 'united': 4, 'kingdom': 2, 'scholastic': 1, 'press': 1, 'states': 2, 'versions': 1, 'around': 2, 'world': 4, 'printed': 1, 'grafica': 1, 'veneta': 1, 'italy': 1, 'many': 3, 'genres': 1, 'including': 1, 'drama': 1, 'coming-of-age': 1, 'fiction': 1, 'includes': 2, 'elements': 1, 'mystery': 1, 'thriller': 1, 

In [150]:
vocab_sorted=sorted(vocab.items(), key=lambda x:x[1], reverse=True)
print(vocab_sorted)

[('harry', 10), ('potter', 9), ('series', 7), ('books', 6), ('rowling', 4), ('united', 4), ('world', 4), ('wizard', 3), ('story', 3), ('many', 3), ('million', 3), ('copies', 3), ('seven', 2), ('fantasy', 2), ('novels', 2), ('british', 2), ('school', 2), ('main', 2), ('known', 2), ('kingdom', 2), ('states', 2), ('around', 2), ('includes', 2), ('numerous', 2), ('themes', 2), ('release', 2), ('success', 2), ('worldwide', 2), ('making', 2), ('history', 2), ('2016', 2), ('franchise', 2), ('films', 2), ('written', 1), ('author', 1), ('chronicle', 1), ('lives', 1), ('young', 1), ('friends', 1), ('hermione', 1), ('granger', 1), ('ron', 1), ('weasley', 1), ('students', 1), ('hogwarts', 1), ('witchcraft', 1), ('wizardry', 1), ('arc', 1), ('concerns', 1), ('conflict', 1), ('lord', 1), ('voldemort', 1), ('dark', 1), ('intends', 1), ('become', 1), ('immortal', 1), ('overthrow', 1), ('governing', 1), ('body', 1), ('ministry', 1), ('magic', 1), ('subjugate', 1), ('wizards', 1), ('muggles', 1), ('non-

In [152]:
word_to_index={}
i=1
for (word, frequency) in vocab_sorted:
  if frequency >1 :
    word_to_index[word]=i
    i+=1
print(word_to_index)

{'harry': 1, 'potter': 2, 'series': 3, 'books': 4, 'rowling': 5, 'united': 6, 'world': 7, 'wizard': 8, 'story': 9, 'many': 10, 'million': 11, 'copies': 12, 'seven': 13, 'fantasy': 14, 'novels': 15, 'british': 16, 'school': 17, 'main': 18, 'known': 19, 'kingdom': 20, 'states': 21, 'around': 22, 'includes': 23, 'numerous': 24, 'themes': 25, 'release': 26, 'success': 27, 'worldwide': 28, 'making': 29, 'history': 30, '2016': 31, 'franchise': 32, 'films': 33}


In [158]:
vocab_size=10
word_frequency=[word for word, index in word_to_index.items() if index>vocab_size]
for word in word_frequency:
  del word_to_index[word]
print(word_to_index)

{'harry': 1, 'potter': 2, 'series': 3, 'books': 4, 'rowling': 5, 'united': 6, 'world': 7, 'wizard': 8, 'story': 9, 'many': 10}


In [159]:
word_to_index['OOV']=len(word_to_index)+1

In [160]:
encoded_sentences=[]
for sentence in preprocessed_sentences:
  encoded_sentence=[]
  for word in sentence:
    try:
      encoded_sentence.append(word_to_index[word])
    except KeyError:
      encoded_sentence.append(word_to_index['OOV'])
  encoded_sentences.append(encoded_sentence)
print(encoded_sentences)

[[1, 2, 3, 11, 11, 11, 11, 11, 11, 5], [11, 11, 11, 11, 8, 1, 2, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11], [11, 9, 11, 11, 1, 11, 11, 11, 11, 8, 11, 11, 11, 11, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11], [3, 11, 11, 11, 11, 6, 11, 11, 11, 6, 11], [11, 11, 7, 11, 11, 11, 11], [3, 10, 11, 11, 11, 11, 11, 11, 11, 11, 9, 11, 11, 11, 11, 11, 11, 11, 7, 1, 2, 11, 11, 11, 11, 10, 11, 11, 11], [11, 5, 11, 11, 11], [11, 11, 3, 11, 11, 11, 11], [11, 11, 11, 11, 1, 2, 11, 11, 11, 11, 4, 11, 11, 11, 11, 11, 11, 11, 11], [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11], [11, 11, 4, 11, 11, 11, 11, 11, 11, 11, 11, 3, 11, 11, 11], [11, 11, 4, 11, 11, 11, 11, 4, 11, 11, 11, 11, 11, 11, 11, 11, 6, 11, 11, 11, 11, 6, 11, 11, 11, 11, 11], [11, 11, 4, 11, 11, 11, 11, 3, 11, 11, 11], [11, 11, 11, 1, 2, 11, 11, 11, 11, 1, 2, 11, 11, 11, 11, 11], [1, 2, 11, 11, 11, 11, 9, 11, 5], [11, 4, 11, 11, 1, 2, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 5, 11, 3, 11, 11, 11, 11, 11, 11, 11, 11

In [161]:
##여기부터 패딩
tokenizer=Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
encoded=tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 2, 3, 13, 14, 15, 34, 16, 35, 5], [15, 36, 37, 38, 8, 1, 2, 39, 40, 41, 42, 43, 44, 45, 17, 46, 47], [18, 9, 48, 49, 1, 50, 51, 52, 53, 8, 54, 55, 56, 57, 8, 58, 59, 19, 60, 61, 62, 63, 64, 65, 66], [3, 67, 68, 69, 70, 6, 20, 71, 72, 6, 21], [73, 22, 7, 74, 75, 76, 77], [3, 10, 78, 79, 14, 80, 81, 82, 16, 17, 9, 23, 83, 84, 85, 86, 87, 88, 7, 1, 2, 89, 24, 25, 23, 10, 90, 91, 92], [93, 5, 18, 94, 95], [96, 25, 3, 97, 98, 99, 100], [101, 26, 102, 103, 1, 2, 104, 105, 106, 107, 4, 108, 109, 110, 111, 112, 113, 27, 28], [114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125], [126, 127, 4, 128, 129, 11, 12, 28, 29, 130, 131, 3, 30, 132, 133], [134, 135, 4, 136, 137, 138, 139, 4, 30, 140, 141, 142, 143, 144, 11, 12, 6, 20, 145, 11, 12, 6, 21, 146, 147, 148, 26], [149, 13, 4, 150, 151, 152, 153, 3, 154, 155, 156], [31, 157, 158, 1, 2, 32, 159, 160, 29, 1, 2, 161, 162, 163, 164, 165], [1, 2, 166, 167, 168, 169, 9, 170, 5], [27, 4, 33, 171, 1, 2, 32, 172, 24, 173, 174, 175, 176, 177

In [162]:
max_len=max(len(item) for item in encoded)
#encoded된 문장 중에 가장 긴 문장의 길이는 41이다
print('최대 길이 : ', max_len)

최대 길이 :  41


In [164]:
#최대 길이에 맞추어 패딩
for sentence in encoded:
  while len(sentence) < max_len:
    sentence.append(0)
padded_up=np.array(encoded)
print(padded_up[:10])
#숫자 0을 사용한 제로 패딩

[[  1   2   3  13  14  15  34  16  35   5   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0]
 [ 15  36  37  38   8   1   2  39  40  41  42  43  44  45  17  46  47   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0]
 [ 18   9  48  49   1  50  51  52  53   8  54  55  56  57   8  58  59  19
   60  61  62  63  64  65  66   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0]
 [  3  67  68  69  70   6  20  71  72   6  21   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0]
 [ 73  22   7  74  75  76  77   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0]
 [  3  10  78  79  14  80  81  82  16  17   9  23  83  84  85  86  87  88
    7   1   2  89  24  25  23  10  90  91  92   0   0   0   0   0   0  

In [165]:
#케라스의 전처리 도구 패딩
from tensorflow.keras.preprocessing.sequence import pad_sequences
encoded=tokenizer.texts_to_sequences(preprocessed_sentences)


In [170]:
padded=pad_sequences(encoded)
print(padded[:10])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   1   2   3  13  14
   15  34  16  35   5]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0  15  36  37  38   8   1   2  39  40  41  42  43
   44  45  17  46  47]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  18   9
   48  49   1  50  51  52  53   8  54  55  56  57   8  58  59  19  60  61
   62  63  64  65  66]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   3  67  68  69  70   6
   20  71  72   6  21]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  73  22
    7  74  75  76  77]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  10  78  79  14  80
   81  82  16  17   9  23  83  84  85  86  87  88   7   1   2  89  24  

In [174]:
padded=pad_sequences(encoded, padding='post', maxlen=17)
#최대길이를 17로 설정하고 post를 넣으며 뒤에 0이 붙는다.
#데이터가 maxlen때문에 손실될 경우 truncationg='post'를 이용하여 뒤에서부터 데이터가 삭제된다.
#value=len(tokenizer.word_index)+1을 사용하여 길이보다 1이 큰 수로 0대신 패딩을 할 수 있다.
print(padded[:10])

[[  1   2   3  13  14  15  34  16  35   5   0   0   0   0   0   0   0]
 [ 15  36  37  38   8   1   2  39  40  41  42  43  44  45  17  46  47]
 [ 53   8  54  55  56  57   8  58  59  19  60  61  62  63  64  65  66]
 [  3  67  68  69  70   6  20  71  72   6  21   0   0   0   0   0   0]
 [ 73  22   7  74  75  76  77   0   0   0   0   0   0   0   0   0   0]
 [ 83  84  85  86  87  88   7   1   2  89  24  25  23  10  90  91  92]
 [ 93   5  18  94  95   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 96  25   3  97  98  99 100   0   0   0   0   0   0   0   0   0   0]
 [102 103   1   2 104 105 106 107   4 108 109 110 111 112 113  27  28]
 [114 115 116 117 118 119 120 121 122 123 124 125   0   0   0   0   0]]
