<a href="https://colab.research.google.com/github/UiinKim/UiinKim/blob/main/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

timesteps=10 #시점의 수 -> 문장의 길이(input_length)
input_dim=4 #입력의 수 -> 벡터의 차원
hidden_units=8 #은닉 상태의 크기 -> 은닉에서 반복할 횟수(output_dims)

#입력에 해당되는 2D 텐서
inputs=np.random.random((timesteps, input_dim))

#초기 은닉 상태(맨 처음 은닉층 갔을 때 가중치를 곱한 값)는 0(벡터)로 초기화
hidden_state_t=np.zeros((hidden_units, ))

print('초기 은닉 상태 : ', hidden_state_t)

초기 은닉 상태 :  [0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
Wx=np.random.random((hidden_units, input_dim)) #x(입력)에 대한 가중치 (출력할 벡터의 차원 x 입력한 벡터의 차원)
Wh=np.random.random((hidden_units, hidden_units)) #h(은닉) 상태에 대한 가중치(출력할 벡터의 차원 x 출력할 벡터의 차원)
b=np.random.random((hidden_units)) #편향.출력할 벡터의 차원과 같음

In [ ]:
total_hidden_states=[]
for input_t in inputs:

  #Wx*Xt + Wh * Ht-1 + b
  output_t=np.tanh(np.dot(Wx,input_t)+np.dot(Wh,hidden_state_t)+b)

  #각 시점 t별 메모리 셀의 출력의 크기는 (timestep_t, output_dim)
  #각 시점의 은닉 상태의 값을 계속 누적
  total_hidden_states.append(list(output_t))
  hidden_state_t=output_t

#출력 시 값을 깔끔하게 해주는 용도.
total_hidden_states=np.stack(total_hidden_states, axis=0)

#(timesteps, output_dim)
print('모든 시점의 은닉 상태')
print(total_hidden_states)



모든 시점의 은닉 상태
[[0.85936852 0.87540767 0.73495677 0.92907276 0.9061174  0.8705374
  0.78814924 0.66819455]
 [0.99977299 0.99992069 0.99982753 0.99992099 0.99955838 0.99984483
  0.99997213 0.99974171]
 [0.99985987 0.99992366 0.99993661 0.99988254 0.99947264 0.9997658
  0.99998508 0.9997023 ]
 [0.99995672 0.99999067 0.99997488 0.99997931 0.99988212 0.99994692
  0.99999677 0.99989061]
 [0.99991471 0.99994527 0.99994209 0.99993967 0.99963212 0.99984702
  0.99998996 0.99981676]
 [0.99991857 0.99997784 0.9999641  0.99995301 0.99978769 0.99990174
  0.99999355 0.99982939]
 [0.99996368 0.99999631 0.999983   0.99998933 0.99994705 0.99997664
  0.9999982  0.99993833]
 [0.99992789 0.99998253 0.9999717  0.99997017 0.99988514 0.99993313
  0.99999435 0.9998991 ]
 [0.99993576 0.99995257 0.99996724 0.99992863 0.99969373 0.99972739
  0.99998851 0.99969872]
 [0.99995333 0.99997494 0.99997118 0.99996509 0.99981871 0.99987006
  0.9999934  0.99983588]]


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [ ]:
train_X=[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X)) #2D 텐서(은닉 반복 횟수(시점), 벡터의 차원)

(4, 5)


In [ ]:
train_X=[[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
#3D텐서로 만들어 (batch_size)를 추가한다.
train_X=np.array(train_X, dtype=float)
print(np.shape(train_X))

(1, 4, 5)


In [ ]:
rnn=SimpleRNN(3) #hidden_state(output_dim)
#rnn=SimpleRNN(3, return_sequence=False, return_state=False)와 동일
hidden_state=rnn(train_X) #마지막 은닉 상태를 얻는다.
print('hidden state : {}, shape{}'.format(hidden_state, hidden_state.shape))

hidden state : [[ 0.84908116  0.9932367  -0.69145715]], shape(1, 3)


In [ ]:
rnn=SimpleRNN(3, return_sequences=True) #return_sequences=True로 timesteps만큼 반복할때마다 은닉상태를 출력한다.
hidden_states=rnn(train_X)
print('hidden_state : {}, shape : {}'.format(hidden_states, hidden_states.shape))

hidden_state : [[[-0.9933314  -0.5879856  -0.61173314]
  [-0.9940619   0.12497369  0.86544895]
  [-0.99415934  0.70310915 -0.9300458 ]
  [-0.09982249  0.26073325  0.19295971]]], shape : (1, 4, 3)


In [ ]:
rnn=SimpleRNN(3, return_sequences=True, return_state=True) #return_state=True일 경우 return_sequences여부와 상관 없이 마지막 은닉 상태의 값을 출력한다. 둘 다 True일 경우 둘 다 출력을 리턴한다.
hiddens_states, last_hidden_states=rnn(train_X)

print('hiddens_states : {}, shape : {}'.format(hidden_states, hidden_states.shape))
print('last_hidden_states : {}, shape : {}'.format(last_hidden_states, last_hidden_states.shape))

hiddens_states : [[[-0.9933314  -0.5879856  -0.61173314]
  [-0.9940619   0.12497369  0.86544895]
  [-0.99415934  0.70310915 -0.9300458 ]
  [-0.09982249  0.26073325  0.19295971]]], shape : (1, 4, 3)
last_hidden_states : [[ 0.9929871  0.9824991 -0.7674601]], shape : (1, 3)


In [ ]:
lstm=LSTM(3, return_sequences=True, return_state=True) #LSTM은 return_state=True이면 마지막 셀 상태까지 출력한다.
hidden_state, last_state, last_cell_state=lstm(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden state : [[[ 0.06385525  0.57098526 -0.35932428]
  [ 0.21980323  0.7826744  -0.26663786]
  [ 0.13306822  0.6068478  -0.48383227]
  [ 0.36194637  0.5154958  -0.17846362]]], shape: (1, 4, 3)
last hidden state : [[ 0.36194637  0.5154958  -0.17846362]], shape: (1, 3)
last cell state : [[ 0.96608454  1.9872048  -1.2035065 ]], shape: (1, 3)


In [ ]:
!pip install pad_sequences

In [ ]:
#RNN을 이용한 텍스트 생성
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

tokenizer=Tokenizer()
tokenizer.fit_on_texts([text]) #각 단어를 하나의 토큰으로 만든다. **리스트 형태로 받는다.(문자열은 배열)
vocab_size=len(tokenizer.word_index)+1 #패딩까지 고려해서
print('단어 집합의 크기 : ',vocab_size)

단어 집합의 크기 :  12


In [ ]:
print(tokenizer.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [ ]:
sequences=[]
for line in text.split('\n'):
  encoded=tokenizer.texts_to_sequences([line])[0] #fit_on_texts로 만들었던 각 단어들의 토큰(정수 인코딩)들을 기준으로 각 문장의 새로운 배열 생성.
  print(encoded)
  for i in range(1,len(encoded)): #정수로 인코딩 된 문장을 두 단어 이상부터 시작해서 마지막까지 다 포함되는 경우까지 차례대로 추가한다.
    sequence=encoded[:i+1]
    print(sequence)
    sequences.append(sequence)
print('학습에 사용할 샘플의 개수 : ', len(sequences))

[2, 3, 1, 4, 5]
[2, 3]
[2, 3, 1]
[2, 3, 1, 4]
[2, 3, 1, 4, 5]
[]
[6, 1, 7]
[6, 1]
[6, 1, 7]
[]
[8, 1, 9, 10, 1, 11]
[8, 1]
[8, 1, 9]
[8, 1, 9, 10]
[8, 1, 9, 10, 1]
[8, 1, 9, 10, 1, 11]
[]
학습에 사용할 샘플의 개수 :  11


In [ ]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [ ]:
max_len=max(len(l) for l in sequences)
print(max_len)

6


In [ ]:
sequences=pad_sequences(sequences, maxlen=max_len, padding='pre') #앞에다가 0을 붙이고 최대 길이는 6으로 한다.
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [ ]:
#맨 마지막 데이터가 정답이므로 마지막 전까지의 단어들을 X, 마지막 단어를 y로 하여 분리한다.
sequences=np.array(sequences)
X=sequences[:,:-1] #행은 전체, 열은 마지막을 제외
y=sequences[:,-1] #행은 전체, 열은 마지막만
print(X)
print(y)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]
[ 3  1  4  5  1  7  1  9 10  1 11]


In [ ]:
y=to_categorical(y, num_classes=vocab_size) #정수 인코딩 된 레이블을 원-핫 벡터로 인코딩
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#모든 단어로 하나의 단어를 예측하는 RNN 모델 설계
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, SimpleRNN

embedding_dim=10
hidden_units=32

model=Sequential()
model.add(Embedding(vocab_size, embedding_dim)) #단어 목록의 크기(쉽게 생각하면 입력 크기), 벡터의 차원
model.add(SimpleRNN(hidden_units)) #은닉층 은닉 상태의 크기는 32(output_dim)
model.add(Dense(vocab_size, activation='softmax')) #출력층, output_dim=단어 목록의 크기만큼으로 분류. 다중클래스분류이므로 softmax 사용
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X,y,epochs=200, verbose=2)

Epoch 1/200
1/1 - 2s - loss: 2.4779 - accuracy: 0.0909 - 2s/epoch - 2s/step
Epoch 2/200
1/1 - 0s - loss: 2.4656 - accuracy: 0.0909 - 8ms/epoch - 8ms/step
Epoch 3/200
1/1 - 0s - loss: 2.4531 - accuracy: 0.2727 - 8ms/epoch - 8ms/step
Epoch 4/200
1/1 - 0s - loss: 2.4404 - accuracy: 0.3636 - 8ms/epoch - 8ms/step
Epoch 5/200
1/1 - 0s - loss: 2.4274 - accuracy: 0.3636 - 8ms/epoch - 8ms/step
Epoch 6/200
1/1 - 0s - loss: 2.4140 - accuracy: 0.3636 - 11ms/epoch - 11ms/step
Epoch 7/200
1/1 - 0s - loss: 2.4002 - accuracy: 0.3636 - 11ms/epoch - 11ms/step
Epoch 8/200
1/1 - 0s - loss: 2.3860 - accuracy: 0.3636 - 11ms/epoch - 11ms/step
Epoch 9/200
1/1 - 0s - loss: 2.3713 - accuracy: 0.4545 - 11ms/epoch - 11ms/step
Epoch 10/200
1/1 - 0s - loss: 2.3560 - accuracy: 0.4545 - 12ms/epoch - 12ms/step
Epoch 11/200
1/1 - 0s - loss: 2.3402 - accuracy: 0.4545 - 12ms/epoch - 12ms/step
Epoch 12/200
1/1 - 0s - loss: 2.3238 - accuracy: 0.4545 - 14ms/epoch - 14ms/step
Epoch 13/200
1/1 - 0s - loss: 2.3066 - accuracy: 

In [ ]:
print(tokenizer.word_index.items())

dict_items([('말이', 1), ('경마장에', 2), ('있는', 3), ('뛰고', 4), ('있다', 5), ('그의', 6), ('법이다', 7), ('가는', 8), ('고와야', 9), ('오는', 10), ('곱다', 11)])


In [ ]:
#문장 생성 함수
def sentence_generation(model, tokenizer, current_word, n): #모델, 토크나이저, 현재 단어, 반복할 횟수
  init_word=current_word
  sentence=''

  #n번 반복
  for _ in range(n):
    #현재 단어에 대한 정수 인코딩
    encoded=tokenizer.texts_to_sequences([current_word])[0]
    encoded=pad_sequences([encoded],maxlen=5, padding='pre')
    #입력한 단어에 대한 예측 단어를 result에 저장
    result=model.predict(encoded, verbose=0)
    result=np.argmax(result, axis=1)#가장 큰 원소가 있는 인덱스를 반환

    for word, index in tokenizer.word_index.items(): #tokenizer에 fit_on_texts로 저장해둔 토큰들 중에 있는지 확인한다.
      if index==result:
        break

    current_word=current_word + ' ' + word #위 반복문에서 찾은 예측 단어와 합하여 다시 반복문에서 사용하도록 한다.

    sentence=sentence + ' ' +word #문장에 저장

  sentence=init_word + sentence
  return sentence


In [ ]:
print(sentence_generation(model, tokenizer, '가는', 4))

가는 말이 고와야 오는 말이


In [ ]:
!pip install kaggle

In [ ]:
!kaggle datasets download -d aashita/nyt-comments

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python3.10/dist-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/usr/local/lib/python3.10/dist-packages/kaggle/api/kaggle_api_extended.py", line 181, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.


In [ ]:
import pandas as pd
import numpy as np
from string import punctuation

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [ ]:
df=pd.read_csv('ArticlesApril2018.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1324 entries, 0 to 1323
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   articleID         1324 non-null   object
 1   articleWordCount  1324 non-null   int64 
 2   byline            1324 non-null   object
 3   documentType      1324 non-null   object
 4   headline          1324 non-null   object
 5   keywords          1324 non-null   object
 6   multimedia        1324 non-null   int64 
 7   newDesk           1324 non-null   object
 8   printPage         1324 non-null   int64 
 9   pubDate           1324 non-null   object
 10  sectionName       1324 non-null   object
 11  snippet           1324 non-null   object
 12  source            1324 non-null   object
 13  typeOfMaterial    1324 non-null   object
 14  webURL            1324 non-null   object
dtypes: int64(3), object(12)
memory usage: 155.3+ KB


In [ ]:
df['headline'].isnull().values.any()

False

In [ ]:
headline=list(df['headline']) #리스트 형태로 저장
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [ ]:
print('총 샘플의 개수 : ', len(headline))

총 샘플의 개수 :  1324


In [ ]:
headline=[word for word in headline if word != 'Unknown']
print('노이즈 값 제거 후 ', len(headline))

노이즈 값 제거 후  1214


In [ ]:
#데이터 전처리
def repreprocessing(raw_sentence):
  preprocessed_sentence=raw_sentence.encode('utf8').decode('ascii','ignore') #어떤 언어든 깨지지 않고 출력이 가능한 utf8로 인코딩. ascii, ignore로 \xe2\x80\x99 등과 같은 바이트 열 제거
  return ''.join(word for word in preprocessed_sentence if word not in punctuation).lower()
  # punctuation으로 구두점(. , ')을 모두 날리고 lower로 소문자화하며 join으로 모든 단어들을 한 문장의 문자열로 합한다.

preprocessed_headline=[repreprocessing(x) for x in headline] #headline의 한 문장씩 전처리를 실행한다.
preprocessed_headline[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [ ]:
#단어 집합 생성 및 tokenizer에 저장
tokenizer=Tokenizer()
tokenizer.fit_on_texts(preprocessed_headline)
vocab_size=len(tokenizer.word_index)+1
print('단어 집합의 크기 : {}'.format(vocab_size))

단어 집합의 크기 : 3494


In [ ]:
#정수 인코딩을 동시하며 하나의 문장을 여러 줄로 분해 하여 train_data 생성
sequences=[]
for sentence in preprocessed_headline:
  encoded=tokenizer.texts_to_sequences([sentence])[0] #정수 인코딩을 하는데 []으로 리스트형태로 받고 [0]인덱스로 설정을 하여 빈공간[] 없이 토큰화
  for i in range(1,len(encoded)):#최소 단어 개수를 2개부터 해서
    sequence=encoded[:i+1] #한 단어씩 늘려가며 리스트에 저장한다.
    sequences.append(sequence)

sequences[:11]

[[99, 269],
 [99, 269, 371],
 [99, 269, 371, 1115],
 [99, 269, 371, 1115, 582],
 [99, 269, 371, 1115, 582, 52],
 [99, 269, 371, 1115, 582, 52, 7],
 [99, 269, 371, 1115, 582, 52, 7, 2],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116],
 [100, 3]]

In [ ]:
#word_to_index 생성
index_to_word={}
for word, index in tokenizer.word_index.items():
  index_to_word[index]=word
print('빈도수 10번째 단어 : ',index_to_word[10])

빈도수 10번째 단어 :  with


In [ ]:
#패딩을 위한 max_len설정
max_len=max(len(sequence)for sequence in sequences)
print('샘플의 최대 길이 : ', max_len)

샘플의 최대 길이 :  24


In [ ]:
sequences=pad_sequences(sequences, maxlen=max_len, padding='pre')
sequences[:3]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          99,  269],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   99,
         269,  371],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,   99,  269,
         371, 1115]], dtype=int32)

In [ ]:
#맨 우측 단어만 레이블로 분리
X=sequences[:,:-1]
y=sequences[:,-1]

In [ ]:
y=to_categorical(y, num_classes=vocab_size) #레이블 원-핫 인코딩

In [ ]:
#모델 설계
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding

In [ ]:
embedding_dim=10
hidden_units=128

model=Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim)) #단어 목록의 크기, 임베딩의 차원
model.add(LSTM(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
244/244 - 14s - loss: 7.6355 - accuracy: 0.0302 - 14s/epoch - 58ms/step
Epoch 2/200
244/244 - 13s - loss: 7.1165 - accuracy: 0.0259 - 13s/epoch - 53ms/step
Epoch 3/200
244/244 - 12s - loss: 6.9865 - accuracy: 0.0333 - 12s/epoch - 50ms/step
Epoch 4/200
244/244 - 13s - loss: 6.8700 - accuracy: 0.0405 - 13s/epoch - 55ms/step
Epoch 5/200
244/244 - 15s - loss: 6.7214 - accuracy: 0.0424 - 15s/epoch - 62ms/step
Epoch 6/200
244/244 - 12s - loss: 6.5473 - accuracy: 0.0469 - 12s/epoch - 49ms/step
Epoch 7/200
244/244 - 12s - loss: 6.3641 - accuracy: 0.0504 - 12s/epoch - 48ms/step
Epoch 8/200
244/244 - 12s - loss: 6.1707 - accuracy: 0.0568 - 12s/epoch - 51ms/step
Epoch 9/200
244/244 - 14s - loss: 5.9793 - accuracy: 0.0592 - 14s/epoch - 57ms/step
Epoch 10/200
244/244 - 12s - loss: 5.7953 - accuracy: 0.0669 - 12s/epoch - 48ms/step
Epoch 11/200
244/244 - 11s - loss: 5.6214 - accuracy: 0.0715 - 11s/epoch - 47ms/step
Epoch 12/200
244/244 - 15s - loss: 5.4552 - accuracy: 0.0750 - 15s/epoch -

In [ ]:
#문장생성 함수
def sentence_generation(model, tokenizer, current_word, n):
  init_word=current_word
  sentence=''
  for _ in range(n):
    encoded=tokenizer.texts_to_sequences([current_word])[0]
    encoded=pad_sequences([encoded],maxlen=max_len-1, padding='pre')

    result=model.predict(encoded, verbose=0)
    result=np.argmax(result, axis=1)

    for word, index in tokenizer.word_index.items():
      if index==result:
        break
    current_word+=' ' + word
    sentence+=' '+word
  sentence=init_word + sentence
  return sentence

In [ ]:
print(sentence_generation(model, tokenizer, 'i', 10))

i disapprove of school vouchers can i still apply for them


In [ ]:
print(sentence_generation(model, tokenizer, 'how', 10))

how to make facebook more accountable will trump ok for midterms


In [1]:
import numpy as np
import urllib.request
from tensorflow.keras.utils import to_categorical

#데이터 로드
urllib.request.urlretrieve("http://www.gutenberg.org/files/11/11-0.txt", filename="11-0.txt")
f=open('11-0.txt', 'rb') #바이트 형식으로 읽는다.
sentences=[]
for sentence in f:
  sentence=sentence.strip() #strip()을 통해 \r, \n을 제거한다.
  sentence=sentence.lower()
  sentence=sentence.decode('ascii','ignore')
  if len(sentence)>0:
    sentences.append(sentence)
f.close()

In [2]:
sentences[:5]

['the project gutenberg ebook of alices adventures in wonderland, by lewis carroll',
 'this ebook is for the use of anyone anywhere in the united states and',
 'most other parts of the world at no cost and with almost no restrictions',
 'whatsoever. you may copy it, give it away or re-use it under the terms',
 'of the project gutenberg license included with this ebook or online at']

In [3]:
total_data=' '.join(sentences) #하나의 문자열로 합치기, 단, 하나의 문장마다 ' '공백 추가
print(len(total_data))

159484


In [4]:
print(total_data[:200])

the project gutenberg ebook of alices adventures in wonderland, by lewis carroll this ebook is for the use of anyone anywhere in the united states and most other parts of the world at no cost and with


In [5]:
char_vocab=sorted(list(set(total_data))) #한 문자열이 되었으므로 중복 제거한 문자들만 정렬하여 리스트 형태로 만든다.
vocab_size=len(char_vocab)
print(vocab_size)

56


In [6]:
char_to_index=dict((char, index) for index, char in enumerate(char_vocab)) #각 문자마다 인덱스의 번호를 매겨준다.
print('문자집합 : ', char_to_index)

문자집합 :  {' ': 0, '!': 1, '"': 2, '#': 3, '$': 4, '%': 5, "'": 6, '(': 7, ')': 8, '*': 9, ',': 10, '-': 11, '.': 12, '/': 13, '0': 14, '1': 15, '2': 16, '3': 17, '4': 18, '5': 19, '6': 20, '7': 21, '8': 22, '9': 23, ':': 24, ';': 25, '?': 26, '[': 27, ']': 28, '_': 29, 'a': 30, 'b': 31, 'c': 32, 'd': 33, 'e': 34, 'f': 35, 'g': 36, 'h': 37, 'i': 38, 'j': 39, 'k': 40, 'l': 41, 'm': 42, 'n': 43, 'o': 44, 'p': 45, 'q': 46, 'r': 47, 's': 48, 't': 49, 'u': 50, 'v': 51, 'w': 52, 'x': 53, 'y': 54, 'z': 55}


In [7]:
index_to_char=dict((value, key) for key, value in char_to_index.items() )
print(index_to_char)

{0: ' ', 1: '!', 2: '"', 3: '#', 4: '$', 5: '%', 6: "'", 7: '(', 8: ')', 9: '*', 10: ',', 11: '-', 12: '.', 13: '/', 14: '0', 15: '1', 16: '2', 17: '3', 18: '4', 19: '5', 20: '6', 21: '7', 22: '8', 23: '9', 24: ':', 25: ';', 26: '?', 27: '[', 28: ']', 29: '_', 30: 'a', 31: 'b', 32: 'c', 33: 'd', 34: 'e', 35: 'f', 36: 'g', 37: 'h', 38: 'i', 39: 'j', 40: 'k', 41: 'l', 42: 'm', 43: 'n', 44: 'o', 45: 'p', 46: 'q', 47: 'r', 48: 's', 49: 't', 50: 'u', 51: 'v', 52: 'w', 53: 'x', 54: 'y', 55: 'z'}


In [10]:
#문장 샘플의 길이를 정하고 해당 길이만큼 문자열 전체를 등분한다.
seq_length=60

n_samples=int(((len(total_data)-1)//seq_length)) #np.floor로 내림 후 반환해도 됨,
print(n_samples)

2658


In [11]:
#X_train은 60단위로 글자들을 자르고 y_train은 X_train에서 1씩 오른쪽으로 시프트 된 글자들을 넣는다.
X_train=[]
y_train=[]

for i in range(n_samples): #sample 수 만큼 반복
  #total_data를 슬라이싱하여 할당
  X_sample=total_data[i*(seq_length):(i+1)*seq_length]
  #정수 encoding
  X_encoded=[char_to_index[c] for c in X_sample]
  X_train.append(X_encoded)
  y_sample=total_data[(i*seq_length)+1:((i+1)*seq_length)+1]
  y_encoded=[char_to_index[c] for c in y_sample]
  y_train.append(y_encoded)

In [13]:
print('X 데이터의 첫번째 샘플 :',X_train[0])
print('y 데이터의 첫번째 샘플 :',y_train[0])
print('-'*50)
print('X 데이터의 첫번째 샘플 디코딩 :',[index_to_char[i] for i in X_train[0]])
print('y 데이터의 첫번째 샘플 디코딩 :',[index_to_char[i] for i in y_train[0]])

X 데이터의 첫번째 샘플 : [49, 37, 34, 0, 45, 47, 44, 39, 34, 32, 49, 0, 36, 50, 49, 34, 43, 31, 34, 47, 36, 0, 34, 31, 44, 44, 40, 0, 44, 35, 0, 30, 41, 38, 32, 34, 48, 0, 30, 33, 51, 34, 43, 49, 50, 47, 34, 48, 0, 38, 43, 0, 52, 44, 43, 33, 34, 47, 41, 30]
y 데이터의 첫번째 샘플 : [37, 34, 0, 45, 47, 44, 39, 34, 32, 49, 0, 36, 50, 49, 34, 43, 31, 34, 47, 36, 0, 34, 31, 44, 44, 40, 0, 44, 35, 0, 30, 41, 38, 32, 34, 48, 0, 30, 33, 51, 34, 43, 49, 50, 47, 34, 48, 0, 38, 43, 0, 52, 44, 43, 33, 34, 47, 41, 30, 43]
--------------------------------------------------
X 데이터의 첫번째 샘플 디코딩 : ['t', 'h', 'e', ' ', 'p', 'r', 'o', 'j', 'e', 'c', 't', ' ', 'g', 'u', 't', 'e', 'n', 'b', 'e', 'r', 'g', ' ', 'e', 'b', 'o', 'o', 'k', ' ', 'o', 'f', ' ', 'a', 'l', 'i', 'c', 'e', 's', ' ', 'a', 'd', 'v', 'e', 'n', 't', 'u', 'r', 'e', 's', ' ', 'i', 'n', ' ', 'w', 'o', 'n', 'd', 'e', 'r', 'l', 'a']
y 데이터의 첫번째 샘플 디코딩 : ['h', 'e', ' ', 'p', 'r', 'o', 'j', 'e', 'c', 't', ' ', 'g', 'u', 't', 'e', 'n', 'b', 'e', 'r', 'g', ' ', 'e',

In [14]:
#문자 단위 RNN은 단어 임베딩을 하지 않기 때문에 바로 원-핫 인코딩을 한다.(임베딩 층을 사용하지 않음)
X_train=to_categorical(X_train)
y_train=to_categorical(y_train)

print(X_train.shape)
#맨 앞은 샘플의 개수로 batch_size에 해당된다. 두번째는 문장으로 만든 각 샘플의 길이로 input_length(timesteps)에 해당된다. 세번째는 각 문자의 원핫인코딩으로 인한 길이로 input_dim 벡터의 차원에 해당된다.
print(y_train.shape)

(2658, 60, 56)
(2658, 60, 56)


In [16]:
#모델 설계(many to many 구조) LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, TimeDistributed

hidden_units=256

model=Sequential()
model.add(LSTM(hidden_units, input_shape=(None, X_train.shape[2]), return_sequences=True)) #X_train.shape[2]=vocab_size, hidden_units=output_dim, input_shape=(timestep, input_dim)
model.add(LSTM(hidden_units, return_sequences=True))
model.add(TimeDistributed(Dense(vocab_size, activation='softmax'))) #TimeDistributed는 모든 timestep의 출력을 출력층에 적용하는 역할이다.

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=80, verbose=2)

Epoch 1/80
84/84 - 49s - loss: 3.0603 - accuracy: 0.1827 - 49s/epoch - 584ms/step
Epoch 2/80
84/84 - 42s - loss: 2.8552 - accuracy: 0.2132 - 42s/epoch - 495ms/step
Epoch 3/80
84/84 - 40s - loss: 2.5067 - accuracy: 0.3067 - 40s/epoch - 481ms/step
Epoch 4/80
84/84 - 52s - loss: 2.3656 - accuracy: 0.3324 - 52s/epoch - 614ms/step
Epoch 5/80
84/84 - 51s - loss: 2.2845 - accuracy: 0.3521 - 51s/epoch - 613ms/step
Epoch 6/80
84/84 - 40s - loss: 2.2160 - accuracy: 0.3676 - 40s/epoch - 482ms/step
Epoch 7/80
84/84 - 54s - loss: 2.1578 - accuracy: 0.3834 - 54s/epoch - 639ms/step
Epoch 8/80
84/84 - 48s - loss: 2.1079 - accuracy: 0.3972 - 48s/epoch - 568ms/step
Epoch 9/80
84/84 - 52s - loss: 2.0667 - accuracy: 0.4077 - 52s/epoch - 620ms/step
Epoch 10/80
84/84 - 46s - loss: 2.0311 - accuracy: 0.4157 - 46s/epoch - 544ms/step
Epoch 11/80
84/84 - 51s - loss: 1.9966 - accuracy: 0.4244 - 51s/epoch - 611ms/step
Epoch 12/80
84/84 - 50s - loss: 1.9630 - accuracy: 0.4326 - 50s/epoch - 590ms/step
Epoch 13/80
8

In [17]:
def sentence_generation(model, length):
  #문자에 대한 랜덤한 정수 생성
  ix=[np.random.randint(vocab_size)] #문자의 종류 개수 안에서의 랜덤한 정수

  #랜덤한 정수로부터 맵핑되는 문자
  y_char=[index_to_char[ix[-1]]]
  print(ix[-1],'번 문자',y_char[-1], '로 예측 시작')

  #(1, length, 56)크기의 X생성(LSTM의 입력 시퀀스)
  X=np.zeros((1,length, vocab_size))

  for i in range(length):
    # X[0][i][예측한 문자의 인덱스]=1, 즉, 예측 문자를 다음 입력 시퀀스에 추가
    X[0][i][ix[-1]]=1
    print(index_to_char[ix[-1]], end='')
    ix=np.argmax(model.predict(X[:,:i+1,:])[0], 1) #0은 1개의 피쳐 중에서 가장 큰 값의 인덱스, 1은 변수 중 가장 큰 값의 인덱스, 2는 행렬 중 가장 큰 값의 인덱스들을 반환한다.
    y_char.append(index_to_char[ix[-1]])
  return (''.join(y_char))

In [19]:
result=sentence_generation(model, 100)
print(result)

39 번 문자 j 로 예측 시작
1/1 [==============================] - 0s 60ms/step
jesty, well into the sentence to see it was a little began again, and the mouse of the works of the g


In [21]:
#문자단위 (many to one 구조)
import numpy as np
from tensorflow.keras.utils import to_categorical

raw_text='I get on with life as a programmer, I like to contemplate beer. But when I start to daydream, My mind turns straight to wine. Do I love wine more than beer? I like to use words about beer. But when I stop my talking, My mind turns straight to wine. I hate bugs and errors. But I just think back to wine, And I\'m happy once again. I like to hang out with programming and deep learning. But when left alone, My mind turns straight to wine.'

In [22]:
#중복을 제거한 문자집합 생성
char_vocab=sorted(list(set(raw_text)))
vocab_size=len(char_vocab)
print('문자 집합 : {}'.format(char_vocab))
print('문자 집합의 크기 : {}'.format(vocab_size))

문자 집합 : [' ', "'", ',', '.', '?', 'A', 'B', 'D', 'I', 'M', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y']
문자 집합의 크기 : 33


In [23]:
#char_to_index 생성
char_to_index=dict((char, index) for index, char in enumerate(char_vocab))
print(char_to_index)

{' ': 0, "'": 1, ',': 2, '.': 3, '?': 4, 'A': 5, 'B': 6, 'D': 7, 'I': 8, 'M': 9, 'a': 10, 'b': 11, 'c': 12, 'd': 13, 'e': 14, 'f': 15, 'g': 16, 'h': 17, 'i': 18, 'j': 19, 'k': 20, 'l': 21, 'm': 22, 'n': 23, 'o': 24, 'p': 25, 'r': 26, 's': 27, 't': 28, 'u': 29, 'v': 30, 'w': 31, 'y': 32}


In [29]:
seq_length=11 #입력 시퀀스가 10, 예측 문자까지 11
sequences=[]
for i in range(seq_length,len(raw_text)):
  #if(i==len(raw_text)-seq_length):
  #  break
  sequence=raw_text[i-seq_length:i]
  sequences.append(sequence)
print('총 훈련의 샘플의 수 : %d' %(len(sequences)))


총 훈련의 샘플의 수 : 426


In [30]:
sequences[:10]

['I get on wi',
 ' get on wit',
 'get on with',
 'et on with ',
 't on with l',
 ' on with li',
 'on with lif',
 'n with life',
 ' with life ',
 'with life a']

In [31]:
#char_to_index를 이용한 정수 인코딩
encoded_sequences=[]
for sequence in sequences:
  encoded=[char_to_index[char] for char in sequence]
  encoded_sequences.append(encoded)

In [32]:
encoded_sequences[:5]

[[8, 0, 16, 14, 28, 0, 24, 23, 0, 31, 18],
 [0, 16, 14, 28, 0, 24, 23, 0, 31, 18, 28],
 [16, 14, 28, 0, 24, 23, 0, 31, 18, 28, 17],
 [14, 28, 0, 24, 23, 0, 31, 18, 28, 17, 0],
 [28, 0, 24, 23, 0, 31, 18, 28, 17, 0, 21]]

In [35]:
#X와 y로 나누어준다.
encoded_sequences=np.array(encoded_sequences)
X_data=encoded_sequences[:,:-1]
y_data=encoded_sequences[:,-1]

In [36]:
#X와 y를 원핫인코딩을 해준다.
X_onehot=np.array([to_categorical(encoded, num_classes=vocab_size) for encoded in X_data])
y_onehot=to_categorical(y_data, num_classes=vocab_size)

In [37]:
print(X_onehot.shape)
#샘플의 수(batch_size), timesteps(seq_length), input_size(벡터의 크기)

(426, 10, 33)


In [42]:
# many to one 모델 설계하기
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

hidden_units=64

model=Sequential()
model.add(LSTM(hidden_units, input_shape=(X_onehot.shape[1], X_onehot.shape[2])))
model.add(Dense(vocab_size, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_onehot, y_onehot, epochs=100, verbose=2)

Epoch 1/100
14/14 - 2s - loss: 3.4733 - accuracy: 0.0962 - 2s/epoch - 159ms/step
Epoch 2/100
14/14 - 0s - loss: 3.3721 - accuracy: 0.1854 - 91ms/epoch - 7ms/step
Epoch 3/100
14/14 - 0s - loss: 3.1375 - accuracy: 0.1972 - 90ms/epoch - 6ms/step
Epoch 4/100
14/14 - 0s - loss: 3.0027 - accuracy: 0.1972 - 90ms/epoch - 6ms/step
Epoch 5/100
14/14 - 0s - loss: 2.9602 - accuracy: 0.1972 - 94ms/epoch - 7ms/step
Epoch 6/100
14/14 - 0s - loss: 2.9434 - accuracy: 0.1972 - 95ms/epoch - 7ms/step
Epoch 7/100
14/14 - 0s - loss: 2.9257 - accuracy: 0.1972 - 92ms/epoch - 7ms/step
Epoch 8/100
14/14 - 0s - loss: 2.9201 - accuracy: 0.1972 - 99ms/epoch - 7ms/step
Epoch 9/100
14/14 - 0s - loss: 2.9087 - accuracy: 0.1972 - 91ms/epoch - 6ms/step
Epoch 10/100
14/14 - 0s - loss: 2.8779 - accuracy: 0.1972 - 94ms/epoch - 7ms/step
Epoch 11/100
14/14 - 0s - loss: 2.8666 - accuracy: 0.1972 - 103ms/epoch - 7ms/step
Epoch 12/100
14/14 - 0s - loss: 2.8417 - accuracy: 0.1995 - 101ms/epoch - 7ms/step
Epoch 13/100
14/14 - 0s

In [43]:
def sentence_generation(model, char_to_index, seq_length, seed_text, n):

  #초기 시퀀스
  init_text=seed_text
  sentence=''

  #다음 문자 예측을 n개의 문자만큼 반복
  for _ in range(n):
    #현재 시퀀스에 대한 정수 인코딩과 패딩을 하고 원핫인코딩을 한다.
    encoded=[char_to_index[char] for char in seed_text]
    encoded=pad_sequences([encoded],maxlen=seq_length, padding='pre')
    encoded=to_categorical(encoded, num_classes=len(char_to_index))

    #입력한 X(현재 시퀀스)에 대해서 y(예측한 문자)를 예측하고 result에 저장
    result=model.predict(encoded, verbose=0)
    result=np.argmax(result, axis=1)

    for char, index in char_to_index.items():
      if index==result:
        break

    #현재 시퀀스 + 예측 문자를 현재 시퀀스로 변경
    seed_text+=char

    #예측 문자를 문장에 저장
    sentence+=char

  #n번 다음 문자의 예측이 끝나면 완성된 문장을 리턴
  sentence=init_text+sentence
  return sentence

In [44]:
print(sentence_generation(model, char_to_index,10, 'I get on w', 80))

I get on with life as a programmer, I like to hang out with programming and deep learning.
