<a href="https://colab.research.google.com/github/UiinKim/UiinKim/blob/main/%EB%B0%91%EB%B0%94%EB%8B%A5%EB%B6%80%ED%84%B0_%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94_%EB%94%A5%EB%9F%AC%EB%8B%9D_2%EA%B6%8C_%EC%B1%95%ED%84%B0_1_1_%EC%88%98%ED%95%99%EA%B3%BC%ED%8C%8C%EC%9D%B4%EC%8D%AC%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



*   벡터 : 1차원 배열
*   행렬 : 2차원 배열
*   3차원 배열이상 = n차원 텐서





In [1]:
import numpy as np


In [2]:
x=np.array([1,2,3])
x.__class__

numpy.ndarray

In [3]:
x.shape #차원의 모양

(3,)

In [4]:
x.ndim #차원

1

In [5]:
W=np.array([[1,2,3],[4,5,6]])
W.shape

(2, 3)

In [6]:
W.ndim

2

In [7]:
W=np.array([[1,2,3],[4,5,6]])
X=np.array([[0,1,2],[3,4,5]])

In [9]:
#원소별 연산이 이루어짐
print(W+X)
print(W*X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


In [10]:
#브로드캐스트
A=np.array([[1,2],[3,4]])
A*10

array([[10, 20],
       [30, 40]])

In [12]:
#브로드캐스트 -> 형상이 다른 배열끼리의 연산 가능
A=np.array([[1,2],[3,4]])
b=np.array([10,20])
A*b

array([[10, 40],
       [30, 80]])



*   벡터의 내적 : 두 벡터의 곱한 각 원소를 모두 더한다.
*   두 벡터의 내적 = 1 -> 완전히 같은 방향
*   두 벡터의 내적 = 0 -> 반대방향





In [13]:
#벡터의 내적
a=np.array([1,2,3])
b=np.array([4,5,6])
np.dot(a,b)

32

In [14]:
#행렬곱->np.dot과 같음
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])



*   입력층(뉴런 여러개) -> 은닉층(뉴런 여러개) -> 출력층(뉴런 여러개)
*   화살표마다 가중치가 존재
*   각 층에는 이전 뉴런에 영향을 받지 않고 더하는 정수인 편향이 존재
*   대응하는 차원의 원소 수가 일치해야함
*   x(1x2)->입력    W(2x4)->가중치  =   h(1x4)->은닉층







In [19]:
#완전연결계층에 의한 변환의 미니배치(전체 데이터를 작은 그룹으로 나눠 그룹 단위로 반복 학습하는 방식) 버전
x=np.random.randn(10,2) #입력
W1=np.random.randn(2,4) #가중치
b1=np.random.randn(4) #편향
W2=np.random.randn(4,3) #은닉층->출력층의 가중치
b2=np.random.randn(3) #은닉층 -> 출력층의 편향
h=np.dot(x,W1)+b1 #생성되는 은닉층 뉴런

활성화 함수 : 선형 변환에 비선형 효과를 부여하는 것

In [20]:
#sigmoid 함수 : 0과 1 사이의 함수를 출력
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [21]:
#sigmoid함수를 사용하여 은닉층 뉴런 변환
a=sigmoid(h) #활성화 함수의 출력 : 활성화
s=np.dot(a,W2)+b2 #은닉층->출력층, a는 입력->은닉층의 결과의 활성화

출력된 첫번째 뉴런이 첫번째 클래스이다. 3차원 데이터가 출력되면 클래스를 3개로 분류가 된다.



*   순전파 : 입력층->출력층으로 향하는 전파



In [27]:
#각 계층 별로 구현
#매서드는 forwrad()만 가진다. params에는 매개변수를 보관한다.

#Sigmoid 계층
class Sigmoid:
  def __init__(self):
    self.params=[]

  def forward(self, x):
    return 1/(1+np.exp(-x))

#Affine 계층
class Affine:
  def __init__(self, W, b):
    self.params=[W,b]

  def forward(self, x):
    W, b=self.params
    out=np.matmul(x, W)+b
    return out

In [28]:
#신경망
class TwoLayerNet:
  def __init__(self, input_size, hidden_size, output_size):
    I, H, O=input_size, hidden_size, output_size

    #가중치와 편향 초기화
    W1=np.random.randn(I, H)
    b1=np.random.randn(H)
    W2=np.random.randn(H,O)
    b2=np.random.randn(O)

    #계층 생성
    self.layers=[
        Affine(W1, b1),
        Sigmoid(),
        Affine(W2,b2)
    ]

    #모든 가중치를 리스트에 모은다.
    self.params=[]
    for layer in self.layers:
      self.params+=layer.params #리스트 결합

  def predict(self, x):
    for layer in self.layers:
      x=layer.forward(x)
    return x


In [31]:
#신경망 추론
x=np.random.randn(10,2) #shape=(10,2)인 입력
model=TwoLayerNet(2,4,3) #2개의 뉴런 입력층, 4개 뉴런 은닉층, 3개 뉴런 출력층
s=model.predict(x)